Handle broken FileDescriptorGaugeSet in Java 9
FileDescriptorGaugeSet is broken at least in OpenJDK 9, throwing an exception
like this:

```
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getOpenFileDescriptorCount() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @1a451d4d
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at com.codahale.metrics.jvm.FileDescriptorRatioGauge.invoke(FileDescriptorRatioGauge.java:48)
	at com.codahale.metrics.jvm.FileDescriptorRatioGauge.getRatio(FileDescriptorRatioGauge.java:35)
	at com.codahale.metrics.RatioGauge.getValue(RatioGauge.java:64)
	at com.spotify.metrics.jvm.FileDescriptorGaugeSet$1.getValue(FileDescriptorGaugeSet.java:54)
	at com.spotify.metrics.ffwd.FastForwardReporter.reportGauge(FastForwardReporter.java:231)
	at com.spotify.metrics.ffwd.FastForwardReporter.report(FastForwardReporter.java:193)
	at com.spotify.metrics.ffwd.FastForwardReporter.report(FastForwardReporter.java:181)
	at com.spotify.metrics.ffwd.FastForwardReporter$2.run(FastForwardReporter.java:348)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:300)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Any metrics that would have been reported AFTER this metric will not be reported
at all, which is pretty bad - no rates, etc would be reported when this throws.

Until upstream (ideally codahale metrics, possibly semantic-metrics) is patched
to handle this properly we reimplement the FileDescriptorSetGauge from
semantic-metrics in a way that handles this safely.